# Generated by Django 4.2 on 2024-06-27 05:14

import ckeditor.fields
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myporfolio', '0004_contacto_mensaje_cifrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='contenido',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2024, 6, 27, 5, 14, 1, 699386, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
